---
title: "R Notebook"
output: html_notebook
---
```{r}
library(dplyr)
library(tidyverse)
install.packages("readxl")
library(readxl)
```

```{r}
raw_data<- read_excel("C:/Users/abdullah cihad/OneDrive/Masaüstü/DIME_RAW_DATA.xlsx")
raw_data

```

```{r}
main_data <-raw_data %>%
  select(Doctor, AppointmentDate, IMERating, ATPIMPRating, AtMMI) %>% 
  filter(!is.na(IMERating)) %>% 
  filter(!is.na(ATPIMPRating)) %>% 
  filter(!Doctor == ",") %>% 
  mutate(IME_vs_ATP = case_when(IMERating == ATPIMPRating ~ "DIME_ATP_Equal",
                                IMERating < ATPIMPRating ~ "DIME_Lower",
                                IMERating > ATPIMPRating ~ "DIME_Higher")) %>% 
  mutate(AtMMI = tolower(AtMMI))
main_data
```


```{r}

date<- main_data %>% 
  group_by(Doctor) %>%
  slice(which.max(AppointmentDate))
Last_Date <- date$AppointmentDate
  

```

```{r}
 Difference <- main_data %>% 
  mutate(Fark = IMERating - ATPIMPRating) %>%
  group_by(Doctor) %>% 
  summarise(d_column= mean(Fark)) %>% 
  mutate(Average_Difference = round(d_column,digits = 2)) %>% 
  select(Average_Difference)
  
```



```{r}
 y <- main_data %>% 
  group_by(Doctor) %>% 
  summarise(DIME_H = sum(IME_vs_ATP=="DIME_Higher"),
            DIME_L= sum(IME_vs_ATP== "DIME_Lower"),
            Equal= sum(IME_vs_ATP=="DIME_ATP_Equal"),
            N_MMI= sum(AtMMI=="no"),
            Y_MMI=sum(AtMMI=="yes")) %>% 
  mutate(Total_Case_Number= DIME_H+DIME_L+Equal) %>% 
  mutate(DIME_Higher_ATP=  round(DIME_H/Total_Case_Number*100,digits=2),
         DIME_Lower_ATP= round(DIME_L/Total_Case_Number*100,digits=2),
         DIME_Equal_ATP= round(Equal/Total_Case_Number*100, digits=2),
         Not_At_MMI= round(N_MMI/Total_Case_Number*100,2))


percenteges <- as.data.frame(lapply(y[8:11], FUN=paste0, "%"))



```



```{r}
Final_Data <- main_data %>%
  group_by(Doctor) %>% 
  summarise(Number_Of_Cases=n()) %>% 
  add_column(Last_Date) %>% 
  add_column(Difference) %>% 
  cbind.data.frame(percenteges) 

Final_Data_Ordered <- Final_Data[, c(1,2,3,5,6,7,8,4)]



```























